import os


# ============================================
# BASE PATH
# ============================================

BASE_PATH = os.getcwd()


# ============================================
# PROJECT STRUCTURE
# ============================================

PROJECT_STRUCTURE = {

    "backend": [
        "main.py",
        "routes.py",
        "models.py",
        "config.py"
    ],

    "frontend": [
        "index.html",
        "app.js",
        "style.css"
    ],

    "api": [
        "api_gateway.py"
    ],

    "database": [
        "db.py"
    ],

    "docker": [
        "Dockerfile"
    ],

    "docs": [
        "architecture.md"
    ]
}


# ============================================
# CREATE DIRECTORY
# ============================================

def create_directory(path):

    if not os.path.exists(path):

        os.makedirs(path)

        print(f"📂 Created directory: {path}")


# ============================================
# CREATE FILE
# ============================================

def create_file(path, content=""):

    if not os.path.exists(path):

        with open(path, "w", encoding="utf-8") as file:

            file.write(content)

        print(f"📄 Created file: {path}")


# ============================================
# GENERATE README
# ============================================

def generate_readme(project_name):

    return f'''
# {project_name}

Generated by SYNERGIA AI SOFTWARE FACTORY

## Modules

- Backend
- Frontend
- API
- Database
- Docker

## Status

INITIALIZED
'''


# ============================================
# GENERATE REQUIREMENTS
# ============================================

def generate_requirements():

    return '''
flask
fastapi
uvicorn
requests
'''


# ============================================
# GENERATE DOCKER COMPOSE
# ============================================

def generate_docker():

    return '''
version: "3"

services:

  backend:
    build: ./docker
    ports:
      - "8000:8000"
'''


# ============================================
# CREATE PROJECT
# ============================================

def create_project(project_name):

    print("\n==============================")
    print(" SYNERGIA PROJECT GENERATOR")
    print("==============================\n")

    projects_path = os.path.join(BASE_PATH, "projects")

    create_directory(projects_path)

    project_path = os.path.join(projects_path, project_name)

    create_directory(project_path)

    # ----------------------------------------

    for folder, files in PROJECT_STRUCTURE.items():

        folder_path = os.path.join(project_path, folder)

        create_directory(folder_path)

        for file in files:

            file_path = os.path.join(folder_path, file)

            create_file(file_path)

    # ----------------------------------------

    create_file(
        os.path.join(project_path, "README.md"),
        generate_readme(project_name)
    )

    create_file(
        os.path.join(project_path, "requirements.txt"),
        generate_requirements()
    )

    create_file(
        os.path.join(project_path, "docker-compose.yml"),
        generate_docker()
    )

    print("\n==============================")
    print(" PROJECT GENERATED SUCCESSFULLY")
    print("==============================\n")

    print(f"🚀 Project Path:\n{project_path}")


# ============================================
# RUN
# ============================================

if __name__ == "__main__":

    create_project("restaurant_ai")
